Models:
- Config: configs/face_2d_keypoint/topdown_regression/wflw/td-reg_res50_8xb64-210e_wflw-256x256.py
  In Collection: ResNet
  Metadata:
    Architecture:
    - DeepPose
    - ResNet
    Training Data: WFLW
  Name: td-reg_res50_8x64e-210e_wflw-256x256
  Results:
  - Dataset: WFLW
    Metrics:
      NME: 4.88
    Task: Face 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/face/deeppose/deeppose_res50_wflw_256x256-92d0ba7f_20210303.pth
